package vistas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;


public class MenuPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipalView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(500, 520);
        this.setTitle("Menu Principal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        ImageIcon icono = new ImageIcon(getClass().getResource("/recursos/gestionUlp.jpg"));
        Image miImagen = icono.getImage();
        jDPEscritorio = new javax.swing.JDesktopPane(){
            public void paintComponent (Graphics g) {
                g.drawImage(miImagen,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar2 = new javax.swing.JMenuBar();
        jAlumno = new javax.swing.JMenu();
        jFormAlum = new javax.swing.JMenuItem();
        jMateria = new javax.swing.JMenu();
        jFormMateria = new javax.swing.JMenuItem();
        jAdmi = new javax.swing.JMenu();
        jManejoIns = new javax.swing.JMenuItem();
        jManNotas = new javax.swing.JMenuItem();
        jConsultas = new javax.swing.JMenu();
        jAlumPorMateria = new javax.swing.JMenuItem();
        jSalir = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDPEscritorioLayout = new javax.swing.GroupLayout(jDPEscritorio);
        jDPEscritorio.setLayout(jDPEscritorioLayout);
        jDPEscritorioLayout.setHorizontalGroup(
            jDPEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
        );
        jDPEscritorioLayout.setVerticalGroup(
            jDPEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jAlumno.setText("Alumno");
        jAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlumnoActionPerformed(evt);
            }
        });

        jFormAlum.setText("Formulario Alumno");
        jFormAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormAlumActionPerformed(evt);
            }
        });
        jAlumno.add(jFormAlum);

        jMenuBar2.add(jAlumno);

        jMateria.setText("Materia");

        jFormMateria.setText("Formulario Materia");
        jFormMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormMateriaActionPerformed(evt);
            }
        });
        jMateria.add(jFormMateria);

        jMenuBar2.add(jMateria);

        jAdmi.setText("Administracion");

        jManejoIns.setText("Manejo de inscripciones");
        jManejoIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jManejoInsActionPerformed(evt);
            }
        });
        jAdmi.add(jManejoIns);

        jManNotas.setText("Manipulacion de notas");
        jAdmi.add(jManNotas);

        jMenuBar2.add(jAdmi);

        jConsultas.setText("Consultas");

        jAlumPorMateria.setText("Alumno por materia");
        jAlumPorMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlumPorMateriaActionPerformed(evt);
            }
        });
        jConsultas.add(jAlumPorMateria);

        jMenuBar2.add(jConsultas);

        jSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/salir.png"))); // NOI18N
        jMenuBar2.add(jSalir);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jManejoInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jManejoInsActionPerformed
        // TODO add your handling code here:
        jDPEscritorio.removeAll();
        jDPEscritorio.repaint();
        InscripcionesView inscripciones = new InscripcionesView();
        inscripciones.setVisible(true);
        inscripciones.getContentPane().setBackground(new Color(68, 167, 132));
        jDPEscritorio.add(inscripciones);
    }//GEN-LAST:event_jManejoInsActionPerformed

    private void jFormAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormAlumActionPerformed
        jDPEscritorio.removeAll();
        jDPEscritorio.repaint();
        GestionAlumnoView alumno = new GestionAlumnoView();
        alumno.setVisible(true);
        alumno.getContentPane().setBackground(new Color(68, 167, 132));
        jDPEscritorio.add(alumno);
    }//GEN-LAST:event_jFormAlumActionPerformed

    private void jAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAlumnoActionPerformed

    private void jFormMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormMateriaActionPerformed
        jDPEscritorio.removeAll();
        jDPEscritorio.repaint();
        GestionMateriaView materia = new GestionMateriaView();
        materia.setVisible(true);
        materia.getContentPane().setBackground(new Color(68, 167, 132));
        jDPEscritorio.add(materia);
    }//GEN-LAST:event_jFormMateriaActionPerformed

    private void jAlumPorMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlumPorMateriaActionPerformed
        jDPEscritorio.removeAll();
        jDPEscritorio.repaint();
        ConsultaPorMateriaView materia = new ConsultaPorMateriaView();
        materia.setVisible(true);
        materia.getContentPane().setBackground(new Color(68, 167, 132));
        jDPEscritorio.add(materia);
    }//GEN-LAST:event_jAlumPorMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jAdmi;
    private javax.swing.JMenuItem jAlumPorMateria;
    private javax.swing.JMenu jAlumno;
    private javax.swing.JMenu jConsultas;
    private javax.swing.JDesktopPane jDPEscritorio;
    private javax.swing.JMenuItem jFormAlum;
    private javax.swing.JMenuItem jFormMateria;
    private javax.swing.JMenuItem jManNotas;
    private javax.swing.JMenuItem jManejoIns;
    private javax.swing.JMenu jMateria;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jSalir;
    // End of variables declaration//GEN-END:variables
}
